name: Auto Update IPTV Playlist

on:
  schedule:
    # Chạy tự động vào phút thứ 0 của mỗi giờ (1 tiếng / 1 lần)
    - cron: '0 * * * *'
  # Nút bấm để kích hoạt chạy thủ công trên GitHub khi cần
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Kiểm tra mã nguồn (Checkout Repository)
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện & Trình duyệt Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium --with-deps

      - name: Chạy File Scraper
        run: |
          python scraper.py

      - name: Tự động Commit & Push file playlist.m3u lên Github
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update playlist.m3u [skip ci]"
          file_pattern: 'playlist.m3u'
          
